module.exports = {
  apps: [
    {
      name: 'z-worker',
      script: './services/worker.js',
      args: '-c ../../config/dev/config2.js',
      instances: 2,
      autorestart: true,
      watch: "worker.js",
      max_memory_restart: '1G',
      kill_timeout: 30000,
      exec_mode: "cluster",
    },
    {
      name: 'z-controller',
      script: './services/controller.js',
      args: '-c ../../config/dev/config2.js',
      autorestart: true,
      watch: "controller.js",
      max_memory_restart: '1G',
      kill_timeout: 10000,
      exec_mode: "cluster",
    },
    {
      name: 'z-localstore',
      script: './services/localstore.js',
      args: '-c ../../config/dev/config2.js',
      autorestart: true,
      watch: "localstore.js",
      max_memory_restart: '1G',
      kill_timeout: 10000,
      exec_mode: "cluster",
    },
    {
      name: 'z-remotestore',
      script: './services/remotestore.js',
      args: '-c ../../config/dev/config2.js',
      autorestart: true,
      watch: "remotestore.js",
      max_memory_restart: '1G',
      kill_timeout: 10000,
      exec_mode: "cluster",
    },
    {
      name: "z-nats-local",
      script: "/usr/local/bin/gnatsd",
      args: "-p 6222 -cluster nats://localhost:6248 -m 10222",
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
    },
    {
      name: "z-minio",
      script: "./scripts/start-minio.sh",
      autorestart: true
    },
    {
      name: "z-nats-local-board",
      script: "./node_modules/.bin/natsboard",
      args: "--nats-mon-url http://localhost:10222 --port 3002",
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
    },
  ],
};
